//Inserting History questions into the database.
db.quizzes.insertMany([
    { category: "History", qTxt: "The modern-day city Istanbul last used to be called:", qAns: 4, a1Txt: "Byzantium", a2Txt: "Tsargrad", a3Txt: "Ankara", a4Txt: "Constantinople"},
    { category: "History", qTxt: "Germany was unified in the 1800's by which state:", qAns: 3, a1Txt: "Austria", a2Txt: "Hanover", a3Txt: "Prussia", a4Txt: "Russia"},
    { category: "History", qTxt: "Canada's oldest company is:", qAns: 4, a1Txt: "Tim Hortons", a2Txt: "Royal Bank of Canada (RBC)", a3Txt: "Irving Oil", a4Txt: "Hudson's Bay Company (HBC)"},
    { category: "History", qTxt: "What was the name of the first Roman Emperor?", qAns: 3, a1Txt: "Nero", a2Txt: "Hardian", a3Txt: "Augustus", a4Txt: "Claudius"},
    { category: "History", qTxt: "What historical event was Anne Frank a part of?", qAns: 3, a1Txt: "Partisan resistance to Nazi rule", a2Txt: "The Holodomor", a3Txt: "The Holocaust", a4Txt: "Operation Market Garden"}, 
    { category: "History", qTxt: "Which European city was the birthplace of the Renaissance?", qAns: 4, a1Txt: "Paris", a2Txt: "Berlin", a3Txt: "Madrid", a4Txt: "Florence"}, 
    { category: "History", qTxt: "When did the Apollo 11 land on the moon?", qAns: 2, a1Txt: "1980", a2Txt: "1969", a3Txt: "1972", a4Txt: "1987"},
    { category: "History", qTxt: "What year did World War II end?", qAns: 1, a1Txt: "1945", a2Txt: "1927", a3Txt: "1935", a4Txt: "1910"},
    { category: "History", qTxt: "Who was the last monarch of France before the French Revolution?", qAns: 4, a1Txt: "Louis XIII", a2Txt: "Henry IV", a3Txt: "Louis XV", a4Txt: "Louis XVI"},
    { category: "History", qTxt: "Who was the first Prime Minister of United Kingdom?", qAns: 3, a1Txt: "Margaret Thatcher", a2Txt: "Indira Gandhi", a3Txt: "Sir Robert Walpole", a4Txt: "Theresa May"},
    { category: "History", qTxt: "Who was the first European explorer to reach Canada?", qAns: 2, a1Txt: "Jacques Cartier", a2Txt: "Leif Erikson", a3Txt: "Christopher Columbus", a4Txt: "Sir John A. Macdonald" },
    { category: "History", qTxt: "When was the Canadian Confederation established?", qAns: 2, a1Txt: "1763", a2Txt: "1867", a3Txt: "1917", a4Txt: "1982" },
    { category: "History", qTxt: "What major project linked the eastern and western coasts of Canada for the first time?", qAns: 1, a1Txt: "The Canadian Pacific Railway", a2Txt: "The Trans-Canada Highway", a3Txt: "The St. Lawrence Highway", a4Txt: "The Arctic Highway" },
    { category: "History", qTxt: "What was the outcome of the 1995 Quebec referendum on independence?", qAns: 2, a1Txt: "Quebec voted in favour of seceding from Canada", a2Txt: "Quebec voted against seceding from Canada", a3Txt: "The referendum was cancelled due to legal challenges", a4Txt: "The referendum was postponed indefinitely" },
    { category: "History", qTxt: "When was Canada ceded to Great Britain?", qAns: 2, a1Txt: "1534", a2Txt: "1763", a3Txt: "1867", a4Txt: "1917" },
    { category: "History", qTxt: "In what year did Canada become a fully independent country?", qAns: 4, a1Txt: "1534", a2Txt: "1763", a3Txt: "1867", a4Txt: "1982" },
    { category: "History", qTxt: "What event saw Canadian soldiers earn a reputation for bravery and courage during World War I?", qAns: 1, a1Txt: "Battle of Vimy Ridge", a2Txt: "Battle of the Plains of Abraham", a3Txt: "Battle of the Somme", a4Txt: "Battle of Passchendaele" },
    { category: "History", qTxt: "What transfer of authority from Britain to Canada occurred in 1982?", qAns: 3, a1Txt: "Transfer of power from the Governor-General to the Prime Minister", a2Txt: "Transfer of authority over foreign policy", a3Txt: "Transfer of authority for amending the constitution", a4Txt: "Transfer of authority for conducting federal elections" },
    { category: "History", qTxt: "What percentage of voters in Quebec voted against seceding from Canada in the 1995 referendum?", qAns: 1, a1Txt: "50.58%", a2Txt: "60.11%", a3Txt: "40.94%", a4Txt: "70.67%" },
    { category: "History", qTxt: "In what areas has Canada become a global leader in recent years?", qAns: 1, a1Txt: "Renewable energy, climate change policy, and LGBTQ rights", a2Txt: "Agriculture, manufacturing, and technology", a3Txt: "Banking, insurance, and finance", a4Txt: "Sports, arts, and culture" },
]);

//Inserting Science 
db.quizzes.insertMany([
    { category: "Science", qTxt: "JWST stands for:", qAns: 2, a1Txt: "Jack Weber Science Technology", a2Txt: "James Webb Space Telescope", a3Txt: "Jehova's Witness Space Telescope", a4Txt: "James Weber Scholarship Technique"},
    { category: "Science", qTxt: "The closest star to the Sun is:", qAns: 2, a1Txt: "Rigil Kentaurus", a2Txt: "Proxima Centauri", a3Txt: "Toilman", a4Txt: "Barnard's Star"},
    { category: "Science", qTxt: "The chemical symbol for Gold is:", qAns: 4, a1Txt: "Ag", a2Txt: "Gl", a3Txt: "Fe", a4Txt: "Au"},
    { category: "Science", qTxt: "What is the process by which plants convert sunlight into energy called?", qAns: 2, a1Txt: "Respiration", a2Txt: "Photosynthesis", a3Txt: "Fermentation", a4Txt: "Digestion"},
    { category: "Science", qTxt: "What is the smallest planet in our solar system?", qAns: 3, a1Txt: "Mars", a2Txt: "Venus", a3Txt: "Earth", a4Txt: "Mercury"},
    { category: "Science", qTxt: "What is the closet planet to the sun?", qAns: 1, a1Txt: "Mercury", a2Txt: "Earth", a3Txt: "Jupiter", a4Txt: "Uranus"},
    { category: "Science", qTxt: "What is the most abundant element in the universe?", qAns: 1, a1Txt: "Hydrogen", a2Txt: "Oxygen", a3Txt: "Nitrogen", a4Txt: "Carbon"},
    { category: "Science", qTxt: "What is the largest organ in the human body?", qAns: 3, a1Txt: "Heart", a2Txt: "Liver", a3Txt: "Skin", a4Txt: "Brain"},
    { category: "Science", qTxt: "What is the name of this element 'AU'", qAns: 4, a1Txt: "Helium", a2Txt: "Silver", a3Txt: "Oxygen", a4Txt: "Gold"},
    { category: "Science", qTxt: "What is the process by which water changes from a liquid to a gas called?", qAns: 1, a1Txt: "Evaporation", a2Txt: "Condensation", a3Txt: "Vaporization", a4Txt: "Sublimation"}, 
    { category: "Science", qTxt: "Which of the following is not an element?", qAns: 3, a1Txt: "Oxygen", a2Txt: "Carbon", a3Txt: "Water", a4Txt: "Nitrogen" },
    { category: "Science", qTxt: "Which of the following is an example of a physical change?", qAns: 3, a1Txt: "Burning wood", a2Txt: "Digesting food", a3Txt: "Melting ice", a4Txt: "Rusting metal" },
    { category: "Science", qTxt: "What is the atomic number of Carbon?", qAns: 1, a1Txt: "6", a2Txt: "7", a3Txt: "8", a4Txt: "9" },
    { category: "Science", qTxt: "What type of bond is formed when electrons are shared between atoms?", qAns: 2, a1Txt: "Ionic bond", a2Txt: "Covalent bond", a3Txt: "Metallic bond", a4Txt: "Hydrogen bond" },
    { category: "Science", qTxt: "What is the formula for water?", qAns: 2, a1Txt: "NaCl", a2Txt: "H20", a3Txt: "CO2", a4Txt: "NH3" },
    { category: "Science", qTxt: "Which of the following is a non-renewable resource?", qAns: 3, a1Txt: "Solar energy", a2Txt: "Wind energy", a3Txt: "Coal", a4Txt: "Geothermal energy" },
    { category: "Science", qTxt: "What is the SI unit for force?", qAns: 4, a1Txt: "Joule", a2Txt: "Newton", a3Txt: "Watt", a4Txt: "Metre" },
    { category: "Science", qTxt: "Which of the following is an example of kinetic energy?", qAns: 4, a1Txt: "A rock at the top of a hill", a2Txt: "A car sitting in a parking lot", a3Txt: "A person sitting on a couch", a4Txt: "A ball rolling down a hill" },
    { category: "Science", qTxt: "Which of the following is a characteristic of acids?", qAns: 4, a1Txt: "They have a pH greater than 7", a2Txt: "They taste bitter", a3Txt: "They turn a litmus paper blue", a4Txt: "They react with metals to produce hydrogen gas" },
    { category: "Science", qTxt: "What i What is the formula for density?", qAns: 1, a1Txt: "D? = m/v", a2Txt: "D? = ma", a3Txt: "D? = mg", a4Txt: "D? = F/A" },
]);

//Inserting Math 
db.quizzes.insertMany([
    { category: "Math", qTxt: "(1 + 1)*(2 - 3) = ?:", qAns: 3, a1Txt: "1", a2Txt: "2", a3Txt: "-2", a4Txt: "3"},
    { category: "Math", qTxt: "The derivative of the function 4*x^2 = ?:", qAns: 4, a1Txt: "2*x", a2Txt: "4*x", a3Txt: "6*x", a4Txt: "8*x"},
    { category: "Math", qTxt: "1 + 1 = ?", qAns: 1, a1Txt: "2", a2Txt: "3", a3Txt: "4", a4Txt: "5"},
    { category: "Math", qTxt: "What is the formula for the slope of a line?", qAns: 3, a1Txt: "y = mx + b", a2Txt: "y = ax^2 bx + c", a3Txt: "m = (y2 -y1)/(x2 - x1)", a4Txt: "E = mc^2"},
    { category: "Math", qTxt: "What is the Pythagorean theorem?", qAns: 3, a1Txt: "A^2 = b^2 + c^2", a2Txt: "a^2 + b^2 + c^2", a3Txt: "A^2 + b^2 = c^2", a4Txt: "A^2 - b^2 = c^2"},  
    { category: "Math", qTxt: "What is the sum of the angles in a triangle?", qAns: 4, a1Txt: "270", a2Txt: "360", a3Txt: "90", a4Txt: "180"},  
    { category: "Math", qTxt: "What is the square root of 144?", qAns: 1, a1Txt: "12", a2Txt: "5", a3Txt: "8", a4Txt: "6"},  
    { category: "Math", qTxt: "What is the formula for the volume of a sphere?", qAns: 2, a1Txt: "πr^2", a2Txt: "(4/3)πr^2", a3Txt: "2πr", a4Txt: "4πr^2"},  
    { category: "Math", qTxt: "What is the name of the longest side of a right triangle?", qAns: 4, a1Txt: "Width", a2Txt: "Adjacent", a3Txt: "Opposite", a4Txt: "Hypotenuse"},
    { category: "Math", qTxt: "What is the formula used to calculate the area of a triangle?", qAns: 3, a1Txt: "LxW", a2Txt: "πr^2", a3Txt: "1/2xBxH", a4Txt: "A = (a + b + c) / 2"},
    { category: "Math", qTxt: "What is the value of pi to two decimal places", qAns: 2, a1Txt: "3.14", a2Txt: "3.15", a3Txt: "3.18", a4Txt: "2.3"}, 
    { category: "Math", qTxt: "What is the value of sin(30°)?", qAns: 1, a1Txt: "0.5", a2Txt: "1", a3Txt: "0", a4Txt: "-1" },
    { category: "Math", qTxt: "What is the value of cos(60°)?", qAns: 1, a1Txt: "0.5", a2Txt: "1", a3Txt: "0", a4Txt: "-1" },
    { category: "Math", qTxt: "What is the value of tan(45°)?", qAns: 2, a1Txt: "0.5", a2Txt: "1", a3Txt: "0", a4Txt: "-1" },
    { category: "Math", qTxt: "What is the equation of a line that passes through the points (2, 5) and (4, 9)?", qAns: 1, a1Txt: "y = 2x + 1", a2Txt: "y = 2x + 3", a3Txt: "y = 3x + 2", a4Txt: "y = 3x + 1" },
    { category: "Math", qTxt: "What is the slope of the line 3x - 2y = 6?", qAns: 1, a1Txt: "3/2", a2Txt: "-3/2", a3Txt: "2/3", a4Txt: "-2/3" },
    { category: "Math", qTxt: "What is the equation of a circle with center (-3, 4) and radius of 5?", qAns: 1, a1Txt: "(x+3)^2 + (y-4)^2 = 25", a2Txt: "(x-3)^2 + (y+4)^2 = 25", a3Txt: "(x+4)^2 + (y-3)^2 = 25", a4Txt: "(x-4)^2 + (y+3)^2 = 25" },
    { category: "Math", qTxt: "What is the solution to the equation 2x + 3 = 11?", qAns: 1, a1Txt: "x = 4", a2Txt: "x = 6", a3Txt: "x = 7", a4Txt: "x = 8" },
    { category: "Math", qTxt: "What is the solution to the equation x^2 - 4x + 3 = 0?", qAns: 1, a1Txt: "x = 1, x = 3", a2Txt: "x = 1, x = 2", a3Txt: "x = 2, x = 3", a4Txt: "x = 1, x = 4" },
    { category: "Math", qTxt: "What is the value of the discriminant of the quadratic equation x^2 + 2x + 1 = 0?", qAns: 3, a1Txt: "0", a2Txt: "1", a3Txt: "-1", a4Txt: "2" },
]);

//Inserting Literature 
db.quizzes.insertMany([
    { category: "Literature", qTxt: "'War and Peace' was written by:", qAns: 2, a1Txt: "William Shakespeare", a2Txt: "Leo Tolstoy", a3Txt: "Fyodor Dostoyevsky", a4Txt: "Margaret Gilbert"},
    { category: "Literature", qTxt: "'The Handmaiden's Tale' was written by:", qAns: 3, a1Txt: "Jane Austen", a2Txt: "Mary Shelley", a3Txt: "Margaret Atwood", a4Txt: "Margaret Thatcher"},
    { category: "Literature", qTxt: "Who wrote the 'Harry Potter series'?", qAns: 1, a1Txt: "J.K Rowling", a2Txt: "C.S Lewis", a3Txt: "Stephen King", a4Txt: "R.L Stine"},
    { category: "Literature", qTxt: "Who wrote the book 'The Diary of a Young Girl", qAns: 4, a1Txt: "Primo Levi", a2Txt: "Elie Wiesel", a3Txt: "Helen Keller", a4Txt: "Anne Frank"},
    { category: "Literature", qTxt: "The 'Goosebumps' series is written by:", qAns: 2, a1Txt: "J.R.R Tolkien", a2Txt: "R.L Stine", a3Txt: "George R.R Martin", a4Txt: "Edith Tolkien"},
    { category: "Literature", qTxt: "Which of the following is not a 'Shakespeare' play?", qAns: 3, a1Txt: "Hamlet", a2Txt: "Macbeth", a3Txt: "The great Gatsby", a4Txt: "Romeo and Juliet"},
    { category: "Literature", qTxt: "'The Lightning Thief' was written by:", qAns: 4, a1Txt: "Becky Riordan", a2Txt: "Logan Lerman", a3Txt: "f. Scott Fitzgerald", a4Txt: "Rick Riordan"},
    { category: "Literature", qTxt: "'To Kill a Mockingbird' is written by:", qAns: 2, a1Txt: "Ernest Hemingway", a2Txt: "Harper Lee", a3Txt: "Maya Angelou", a4Txt: "Alice Walker"},
    { category: "Literature", qTxt:  "'The Hunger Games' series was written by:", qAns: 1, a1Txt: "Suzanne Collins", a2Txt: "Mark Cotta Vaz", a3Txt: "Stephanie Meyer", a4Txt: "John Green"},
    { category: "Literature", qTxt: "'The Raven' was written by:", qAns: 3, a1Txt: "William Shakespeare", a2Txt: "Henry James", a3Txt: "Edgar Allan Poe", a4Txt: "Henry James"}, 
    { category: "Literature", qTxt: "Which of the following is a poem by Robert Frost?", qAns: 3, a1Txt: "The Great Gatsby", a2Txt: "The Waste Land", a3Txt: "The Road Not Taken", a4Txt: "A Tale of Two Cities" },
    { category: "Literature", qTxt: "What is the setting of 'The Catcher in the Rye'?", qAns: 1, a1Txt: "New York City", a2Txt: "Los Angeles", a3Txt: "Paris", a4Txt: "London" },
    { category: "Literature", qTxt: "Who is the protagonist of 'The Great Gatsby'?", qAns: 4, a1Txt: "Daisy Buchanan", a2Txt: "Tom Buchanan", a3Txt: "Jay Gatsby", a4Txt: "Nick Carraway" },
    { category: "Literature", qTxt: "What is the title of William Golding's novel about a group of boys stranded on an uninhabited island?", qAns: 1, a1Txt: "Lord of the Flies", a2Txt: "1984", a3Txt: "Brave New World", a4Txt: "Animal Farm" },
    { category: "Literature", qTxt: "Which of the following is a novel by Jane Austen?", qAns: 1, a1Txt: "Sense and Sensibility", a2Txt: "Wuthering Heights", a3Txt: "Frankenstein", a4Txt: "Dracula" },
    { category: "Literature", qTxt: "'The Canterbury Tales' was written by: ", qAns: 2, a1Txt: "William Shakespeare", a2Txt: "Geoffrey Chaucer", a3Txt: "Jane Austen", a4Txt: "Emily Bronte" },
    { category: "Literature", qTxt: "What is the title of J.D. Salinger's novella about a young man who spends three days in New York City?", qAns: 1, a1Txt: "The Catcher in the Rye", a2Txt: "The Great Gatsby", a3Txt: "A Separate Peace", a4Txt: "The Stranger" },
    { category: "Literature", qTxt: "Which of the following is a poem by Langston Hughes?", qAns: 3, a1Txt: "The Love Song of J. Alfred Prufrock", a2Txt: "The Waste Land", a3Txt: "Harlem", a4Txt: "The Road Not Taken" },
    { category: "Literature", qTxt: "'The Adventures of Huckleberry Finn' was written by:", qAns: 1, a1Txt: "Mark Twain", a2Txt: "Edgar Allen Poe", a3Txt: "Herman Melville", a4Txt: "Nathaniel Hawthorne" },
    { category: "Literature", qTxt: "What is the title of John Steinbeck's novel about migrant workers in California during the Great Depression?", qAns: 2, a1Txt: "The Grapes of Wrath", a2Txt: "Of Mice and Men", a3Txt: "The Glass Menagerie", a4Txt: "Long Day's Journey Into Night" },
    { category: "Literature", qTxt: "'The Sound and the Fury' was written by:", qAns: 1, a1Txt: "William Faulkner", a2Txt: "Ernest Hemingway", a3Txt: "John Steinbeck", a4Txt: "Truman Capote" },
]);

